#!/usr/bin/env python3
"""P10 offline fixtures - NO production access. Packet C: the wall must never show the Wazuh SIEM as
healthy when it is not.

Defect this pins (measured 2026-10-02): the Services row and the Integrity chip both read "CORE OK" in
green from 2026-09-24 to 2026-10-02, while the indexer was down, the dashboard returned 503, Filebeat
could not ship and auth telemetry was blind on 8 of 9 hosts. The only input was the manager's daemon
list.

The monitor's checks are pinned by tests/fixtures/wazuh-health-checks-v1.json, GENERATED by
netframe-monitor's classifier (tests/test_wazuh_health.py build_wall_fixture). Its digest is pinned
here, so a change to the shape has to be made on both sides deliberately."""
import hashlib
import importlib.util
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("serve", os.path.join(HERE, "..", "serve.py"))
S = importlib.util.module_from_spec(spec); spec.loader.exec_module(S)
S.sh = lambda *a, **k: ""

fails = []
def chk(n, c): print(("PASS  " if c else "FAIL  ") + n); (fails.append(n) if not c else None)

FIX = os.path.join(HERE, "fixtures", "wazuh-health-checks-v1.json")
PINNED = "ab65ba8b1118739ce5136a1498852af6ef62e047f6792633b3e293249ef6282a"
raw = open(FIX, "rb").read()
chk("0: the producer fixture is the pinned, byte-identical copy", hashlib.sha256(raw).hexdigest() == PINNED)
SC = json.loads(raw)["scenarios"]

def M(wazuh_checks):
    return {"nodes": {"jarvis": {}, "wazuh": wazuh_checks}}

def rows(m):
    svc = {s["n"]: s for s in S.services(m)}["Wazuh SIEM"]
    ig = {c["k"]: c for c in S.integrity(m)}["Wazuh SIEM"]
    return svc, ig

# ---- 1. the measured states ------------------------------------------------------------------
svc, ig = rows(M(SC["healthy"]))
chk("1: healthy -> Services green", svc["s"] == "g" and "d" not in svc)
chk("1: healthy -> Integrity chip green NOMINAL with counts",
    ig["s"] == "g" and ig["v"].startswith("NOMINAL · AUTH 9/9 FRESH · AGENTS 9/9 · DROPS"))

svc, ig = rows(M(SC["broken_2026_10_02"]))
chk("1: the 2026-10-02 state -> Services red", svc["s"] == "r")
chk("1: ... and names the indexer, not 'cause not determined'", svc.get("d", "").startswith("CRITICAL · INDEXER FAILED"))
chk("1: the 2026-10-02 state -> Integrity red, auth majority stale",
    ig["s"] == "r" and ig["v"].startswith("CRITICAL · AUTH MAJORITY STALE") and "AUTH 1/9 FRESH" in ig["v"])

svc, ig = rows(M(SC["recovering_4min_after_ready"]))
chk("1: RED 4 min after READY -> Services yellow (recovering), not red",
    svc["s"] == "y" and "INDEXER RECOVERING" in svc.get("d", ""))
chk("1: ... and the integrity tree is unaffected", ig["s"] == "g")

svc, ig = rows(M(SC["auth_stale_agents_active"]))
chk("1: agents Active but auth stale -> Services green, Integrity NOT green",
    svc["s"] == "g" and ig["s"] == "y" and ig["v"].startswith("DEGRADED · AUTH STALE") and "AUTH 8/9 FRESH" in ig["v"])

svc, ig = rows(M(SC["unmeasured"]))
chk("1: an unparseable report -> both UNKNOWN (u), never green", svc["s"] == "u" and ig["s"] == "u")
chk("1: ... and the unknown is explained", svc.get("d", "").startswith("UNKNOWN"))

# ---- 2. absence, the legacy check, and collection failures ------------------------------------
svc, ig = rows({"nodes": {"jarvis": {}}})
chk("2: no wazuh checks at all -> unknown", svc["s"] == "u" and ig["s"] == "u" and ig["v"] == "UNKNOWN")
legacy = {"wazuh": {"verdict": "OK", "metrics": {"running": 10, "total": 16, "core_down": [], "up": True}}}
svc, ig = rows(M(legacy))
chk("2: a pre-Packet-C daemon-only OK is NOT shown as healthy", svc["s"] == "u" and svc["d"] == "UNKNOWN · LEGACY CHECK")
chk("2: ... and the integrity chip is unknown without wazuh_coverage", ig["s"] == "u")
legacy_warn = {"wazuh": {"verdict": "WARN", "metrics": {"core_down": ["wazuh-analysisd"]}}}
chk("2: a failure from the legacy check is still shown", rows(M(legacy_warn))[0]["s"] == "y")
for v, s in (("AUTH-FAIL", "u"), ("TIMEOUT", "u"), ("UNREACHABLE", "r"), ("UNKNOWN", "u"), ("NEW-VERDICT", "u")):
    m = M({"wazuh": {"verdict": v, "metrics": {}}, "wazuh_coverage": {"verdict": v, "metrics": {}}})
    sv, iv = rows(m)
    chk("2: verdict %s -> %s on both rows" % (v, s), sv["s"] == s and iv["s"] == s)

# ---- 3. the verdict decides the colour; the label can only explain it ------------------------
lie = json.loads(json.dumps(SC["broken_2026_10_02"]))
lie["wazuh"]["verdict"] = "OK"
sv, _ = rows(M(lie))
chk("3: a label that disagrees with the verdict is replaced", sv["s"] == "g" and "d" not in sv)
warn = json.loads(json.dumps(SC["broken_2026_10_02"]))
warn["wazuh"]["verdict"] = "WARN"
sv, _ = rows(M(warn))
chk("3: a yellow row never displays a CRITICAL label", sv["s"] == "y" and sv["d"] == "DEGRADED")
cov = json.loads(json.dumps(SC["broken_2026_10_02"]))
cov["wazuh_coverage"]["verdict"] = "OK"
_, iv = rows(M(cov))
chk("3: a green integrity chip never displays a CRITICAL label", iv["s"] == "g" and iv["v"].startswith("NOMINAL"))
inj = json.loads(json.dumps(SC["broken_2026_10_02"]))
inj["wazuh"]["metrics"]["services_summary"] = "CRITICAL · <script>alert(1)</script> drop table"
sv, _ = rows(M(inj))
chk("3: free text in a summary is reduced to the fixed vocabulary",
    "<" not in sv["d"] and "(" not in sv["d"] and sv["d"].startswith("CRITICAL"))
chk("3: the label is bounded", all(len(x["d"]) <= 72 for x in [sv]))

# ---- 4. CORE OK is gone ------------------------------------------------------------------------
texts = []
for sc in list(SC.values()) + [legacy, legacy_warn]:
    sv, iv = rows(M(sc))
    texts += [sv.get("d", ""), iv["v"]]
chk("4: no input ever produces CORE OK", not any("CORE OK" in t for t in texts))
code = "\n".join(l for l in open(os.path.join(HERE, "..", "serve.py")).read().splitlines()
                 if not l.lstrip().startswith("#"))
chk("4: serve.py code no longer emits CORE OK (the explanatory comment may name it)", "CORE OK" not in code)

# ---- 5. the renderer: the measured reason reaches the attention list ---------------------------
import subprocess, tempfile
state = {"services": S.services(M(SC["broken_2026_10_02"])),
         "integrity": S.integrity(M(SC["broken_2026_10_02"]))}
js = r"""
import { readFileSync } from 'node:fs';
const html = readFileSync(process.argv[2], 'utf8');
const blk = (n) => html.match(new RegExp('/\\* ' + n + '-BEGIN[\\s\\S]*?/\\* ' + n + '-END \\*/'))[0];
const ageFn = html.match(/function nfmAgeText\(sec\)\{[\s\S]*?\n\}/)[0];
const F = new Function(ageFn + blk('NFM-DISPLAY-STATE') + blk('NFM-INCIDENT-PANEL') + blk('NFM-PROPOSAL-PANEL')
  + blk('NFM-INVENTORY') + blk('NFM-MODEL') + blk('NFM-CONDITIONS')
  + '\n return {nfmModel,nfmConditions,nfmNotMeasured};')();
const st = JSON.parse(readFileSync(process.argv[3], 'utf8'));
const snap = JSON.parse(readFileSync(process.argv[4], 'utf8'));
snap.ts = Date.now()/1000; snap.services = st.services; snap.integrity = st.integrity;
const m = F.nfmModel(snap);
const c = F.nfmConditions(m, null, Date.now()/1000);
console.log(JSON.stringify({services: m.services.filter(x=>x.n==='Wazuh SIEM'),
  conds: c.filter(x=>x.sys==='Wazuh SIEM').map(x=>[x.sev,x.text]), nm: F.nfmNotMeasured(m)}));
"""
with tempfile.TemporaryDirectory() as td:
    open(os.path.join(td, "t.mjs"), "w").write(js)
    open(os.path.join(td, "st.json"), "w").write(json.dumps(state))
    try:
        out = subprocess.run(["node", os.path.join(td, "t.mjs"), os.path.join(HERE, "..", "netframe-dashboard.html"),
                              os.path.join(td, "st.json"), os.path.join(HERE, "fixtures", "api-state-sample.json")],
                             capture_output=True, text=True, timeout=60)
        r = json.loads(out.stdout) if out.returncode == 0 else None
    except (OSError, ValueError):
        r = None
if r is None:
    chk("5: renderer harness ran (node required)", False)
else:
    conds = r["conds"]
    chk("5: the renderer keeps the backend's reason on the service row",
        r["services"][0]["s"] == "r" and (r["services"][0]["d"] or "").startswith("CRITICAL · INDEXER FAILED"))
    chk("5: the service condition names the cause instead of 'cause not determined'",
        any(s == "r" and "INDEXER FAILED" in t and "cause not determined" not in t for s, t in conds))
    chk("5: the integrity condition carries the auth count",
        any(s == "r" and "AUTH 1/9 FRESH" in t for s, t in conds))

# ---- 6. the API sample fixture uses the new vocabulary ----------------------------------------
sample = json.load(open(os.path.join(HERE, "fixtures", "api-state-sample.json")))
wz = [c for c in sample["integrity"] if c["k"] == "Wazuh SIEM"][0]
chk("6: the API sample no longer carries CORE OK", wz["v"] != "CORE OK" and wz["v"].startswith("NOMINAL"))

print("%s: %d failed" % ("P10", len(fails)))
raise SystemExit(1 if fails else 0)
